
const ABCD = () => {
    return (
        <div className="bg-red-500 h-full w-full overflow-hidden max-h-full">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam, laboriosam laudantium illum doloremque recusandae exercitationem deserunt nemo assumenda tempore voluptas vel quaerat consequatur, ex aliquid obcaecati quam consequuntur. Necessitatibus, beatae.</p>
            
        </div>
    );
};

export default ABCD;